### ISSUE TITLE
Error connecting to MongoDB Altas

### ISSUE THREAD

**Issue by BRAVO68WEB** [b3h3m0th/britta_discord-music-bot#4]
Getting an error

```
(node:4047) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access thedatabase from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at NativeConnection.Connection.openUri (/home/jbandyopadhayaya/britta_discord-music-bot/node_modules/mongoose/lib/connection.js:828:32)
    at Mongoose.connect (/home/jbandyopadhayaya/britta_discord-music-bot/node_modules/mongoose/lib/index.js:335:15)
    at Object.init (/home/jbandyopadhayaya/britta_discord-music-bot/utils/mongoDB/mongoose.js:15:20)
    at Object.<anonymous> (/home/jbandyopadhayaya/britta_discord-music-bot/index.js:112:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:4047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Did you changed something about connecting to MongoDB?

**Comment by b3h3m0th** [comment]
You need the connection string in order to be able to connect to the database.
The database system needs an rework anyway and isn't working properly yet.
I'm working on it.

**Comment by BRAVO68WEB** [comment]
Ok
I watching on other features
thx
